name: ROS test workflow1

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      CATKIN_WS: /home/runner/work/catkin_ws
    steps:
    - uses: actions/checkout@v2

    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: melodic

    - name: Init workspace
      run: |
        source /opt/ros/melodic/setup.bash
        mkdir -p ${CATKIN_WS}/src && cd ${CATKIN_WS} && catkin_make
        ln -s ${GITHUB_WORKSPACE} ${CATKIN_WS}/src/

    - name: Run tests
      run: |
        source ${CATKIN_WS}/devel/setup.bash
        bash -xve .test/githuaction_package_make.bash
        source ${CATKIN_WS}/devel/setup.bash
        rostest pimouse_ros test.lanch
