name: ROS test workflow2

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      CATKIN_WS: /home/runner/work/catkin_ws
    steps:
    - uses: actions/checkout@v2

    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: melodic

    - name: Init workspace
      run: |
        source /opt/ros/melodic/setup.bash
        mkdir -p ${CATKIN_WS}/src && cd ${CATKIN_WS} && catkin_make
        ln -s ${GITHUB_WORKSPACE} ${CATKIN_WS}/src/

    - name: Run tests
      run: |
        source ${CATKIN_WS}/devel/setup.bash
        cd ./scripts
        ln -s buzzer1.py buzzer.py
        cd ${CARKIN_WS}
        rostest pimouse_ros test.launch
