name: ROS test workflow2

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      CATKIN_WS: /home/runner/work/catkin_ws
    steps:
    - uses: actions/checkout@v4

    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: noetic

    - name: Init workspace
      run: |
        source /opt/ros/noetic/setup.bash
        mkdir -p ${CATKIN_WS}/src && cd ${CATKIN_WS} && catkin_make
        ln -s ${GITHUB_WORKSPACE} ${CATKIN_WS}/src/
        catkin_make
        source ~/.bashrc

    - name: Run tests
      run: |
        source ${CATKIN_WS}/devel/setup.bash
        # bash -xve ./test/travis_prepare_dummy_files.bash
        rostest pimouse_ros test.launch
